### ISSUE TITLE
Issue of docker client in build container not reaching a daemon

### ISSUE THREAD

**Issue by RomainMendez** [testcontainers/dind-drone-plugin#26]
Hi everyone,
I'm troubleshooting my Drone CI pipeline using the given example, and I've found that my build container is trying to reach localhost.
And while I observe the containers being brought up on the machine (and exposing ports 2375 and 2376), the "DOCKER_IP" value in "command.sh" is empty
I'm not sure how to fix this.

**Comment by RomainMendez** [comment]
![image](https://github.com/testcontainers/dind-drone-plugin/assets/31048092/d90967b9-fa52-4146-a7f5-7680bd1dbd45)

So the IP field is empty, I've checked the machine under which it is running and I see a docker0 socket existing.

**Comment by RomainMendez** [comment]
After more debugging, it appears to be a bug in how testcontainers uses the daemon, as using the docker pluging directly seems to work just fine. [There's an issue about this topic on the main repo](https://github.com/testcontainers/testcontainers-python/issues/590)

**Comment by animavitis** [comment]
U do not have to use this at all. Same this can be done by this:

```
kind: pipeline
name: default
steps:
  - name: integration testing
    image: python:3.11.7-bookworm
    privileged: true
    commands:
      - ./run_test.sh
    volumes:
      - name: docker
        path: /var/run/docker.sock

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
```
